dj_crm/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from django.contrib import admin
from django.urls import include, path

from leads.views import LandingPageView, SignupView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("reset-password/", PasswordResetView.as_view(), name="reset-password"),
    path("reset-password-done/", PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password-reset-complete/", PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("", LandingPageView.as_view(), name="landing-page"),
    path("leads/", include("leads.urls", namespace="leads")),
    path("agents/", include("agents.urls", namespace="agents")),
]

leads/urls.py
from django.urls import path
from .views import (
    LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView, AssignAgentView,
    CategoryListView, CategoryDetailView, LeadCategoryUpdateView
)


app_name = "leads"


urlpatterns = [
    path("", LeadListView.as_view(), name="lead-list"),
    path("<int:pk>", LeadDetailView.as_view(), name="lead-detail"),
    path("<int:pk>/update/", LeadUpdateView.as_view(), name="lead-update"),
    path("<int:pk>/delete/", LeadDeleteView.as_view(), name="lead-delete"),
    path("<int:pk>/assign-agent/", AssignAgentView.as_view(), name="assign-agent"),
    path("<int:pk>/category/", LeadCategoryUpdateView.as_view(), name="lead-category-update"),
    path("create/", LeadCreateView.as_view(), name="lead-create"),

    path("categories/", CategoryListView.as_view(), name="category-list"),
    path("categories/<int:pk>", CategoryDetailView.as_view(), name="category-detail"),
]

leads/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save


class User(AbstractUser):
    is_organiser = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey("Agent", null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey("Category", null=True, blank=True, related_name="leads", on_delete=models.SET_NULL)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.get_full_name()


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email


class Category(models.Model):
    name = models.CharField(max_length=30)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(post_user_created_signal, sender=User)

leads/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField

from .models import Agent, Lead


class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        db_table = "lead_master"
        managed = True
        verbose_name = "Lead"
        verbose_name_plural = "Leads"
        fields = ("first_name", "last_name", "email", "phone_number", "age", "agent", "description")


class SignupForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username", )
        field_classes = {"username": UsernameField}


class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        user = request.user
        agents = Agent.objects.filter(organization=user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents


class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            "category",
        )

leads/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.urls import reverse
from django.views.generic import (
    CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView, FormView
)

from agents.mixins import OrganiserAndLoginRequiredMixin

from .forms import LeadModelForm, SignupForm, AssignAgentForm, LeadCategoryUpdateForm
from .models import Lead, Category


class SignupView(CreateView):
    template_name = "registration/signup.html"
    """
    SINCE WE DON'T USE DEFAULT USER MODEL, WE CAN'T USE DEFAULT USER SIGNUP FORM... IT WILL RAISE AN ERROR WHILE
    REGISTRATION.

    HENCE WE OVERRIDE THE DEFAULT FORM AND ASSIGN OUR USER MODEL. THAT WAY IT WILL WORK.
    """
    # form_class = UserCreationForm
    form_class = SignupForm

    def get_success_url(self):
        return reverse("login")


class LandingPageView(TemplateView):
    template_name = "landing.html"


class LeadListView(LoginRequiredMixin, ListView):
    template_name = "leads/lead_list.html"
    context_object_name = "leads"

    def get_queryset(self):
        user = self.request.user

        if user.is_organiser:
            queryset = Lead.objects.filter(organization=user.userprofile, agent__isnull=False)
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization, agent__isnull=False)
            """ FILTER FOR THE AGENT THAT'S LOGGED IN """
            queryset = queryset.filter(agent__user=user)

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(LeadListView, self).get_context_data(object_list=object_list, kwargs=kwargs)
        user = self.request.user

        if user.is_organiser:
            queryset = Lead.objects.filter(organization=user.userprofile, agent__isnull=True)
            context.update({
                "unassigned_leads": queryset
            })
        return context


class LeadDetailView(LoginRequiredMixin, DetailView):
    template_name = "leads/lead_detail.html"
    context_object_name = "lead"

    def get_queryset(self):
        user = self.request.user

        if user.is_organiser:
            queryset = Lead.objects.filter(organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization)
            """ FILTER FOR THE AGENT THAT'S LOGGED IN """
            queryset = queryset.filter(agent__user=user)

        return queryset

    @staticmethod
    def get_success_url():
        return reverse("leads:lead-list")


class LeadCreateView(OrganiserAndLoginRequiredMixin, CreateView):
    template_name = "leads/lead_create.html"
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse("leads:lead-list")

    def form_valid(self, form):
        lead = form.save(commit=False)
        lead.organization = self.request.user.userprofile
        lead.save()
        send_mail(
            subject="New Lead has been created...",
            message="Go to site to view the lead...",
            from_email="test@test.com",
            recipient_list=["tes2t@test.com"]
        )
        return super(LeadCreateView, self).form_valid(form)

    # def post(self, request, *args, **kwargs):
    #     ret = super(LeadCreateView, self).post(request, args, kwargs)
    #     send_mail(
    #         subject="New Lead has been created...",
    #         message="Go to site to view the lead...",
    #         from_email="test@test.com",
    #         recipient_list=["tes2t@test.com"]
    #     )
    #     return ret


class LeadUpdateView(OrganiserAndLoginRequiredMixin, UpdateView):
    template_name = "leads/lead_update.html"
    form_class = LeadModelForm

    def get_queryset(self):
        user = self.request.user
        queryset = Lead.objects.filter(organization=user.userprofile)
        return queryset

    def get_success_url(self):
        return reverse("leads:lead-list")


class LeadDeleteView(OrganiserAndLoginRequiredMixin, DeleteView):
    template_name = "leads/lead_delete.html"

    def get_queryset(self):
        user = self.request.user
        queryset = Lead.objects.filter(organization=user.userprofile)
        return queryset

    def get_success_url(self):
        return reverse("leads:lead-list")


class AssignAgentView(OrganiserAndLoginRequiredMixin, FormView):
    template_name = "leads/assign_agent.html"
    form_class = AssignAgentForm

    def get_success_url(self):
        return reverse("leads:lead-list")

    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs()
        kwargs.update({
            "request": self.request
        })
        return kwargs

    def form_valid(self, form):
        agent = form.cleaned_data.get("agent")
        lead = Lead.objects.get(pk=self.kwargs.get("pk"))
        lead.agent = agent
        lead.save()
        return super(AssignAgentView, self).form_valid(form)


class CategoryListView(LoginRequiredMixin, ListView):
    template_name = "leads/category_list.html"
    context_object_name = "categories"

    def get_queryset(self):
        user = self.request.user

        if user.is_organiser:
            queryset = Category.objects.filter(organization=user.userprofile)
        else:
            queryset = Category.objects.filter(organization=user.agent.organization)

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryListView, self).get_context_data(object_list=object_list, kwargs=kwargs)

        user = self.request.user

        if user.is_organiser:
            queryset = Lead.objects.filter(organization=user.userprofile, agent__isnull=False)
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization, agent__isnull=False)

        context.update({
            "unassigned_leads_count": queryset.filter(category__isnull=True).count()
        })

        return context


class CategoryDetailView(LoginRequiredMixin, DetailView):
    template_name = "leads/category_detail.html"
    context_object_name = "category"

    def get_queryset(self):
        user = self.request.user

        if user.is_organiser:
            queryset = Category.objects.filter(organization=user.userprofile)
        else:
            queryset = Category.objects.filter(organization=user.agent.organization)

        return queryset

    # def get_context_data(self, *, object_list=None, **kwargs):
    #     context = super(CategoryDetailView, self).get_context_data(object_list=object_list, kwargs=kwargs)
    #     """ `leads` is the related_name given in Lead model. This is special syntax to fetch in ForeignKey fields. """
    #     leads = self.get_object().leads.all()
    #     context.update({
    #         "leads": leads
    #     })
    #     return context


class LeadCategoryUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "leads/lead_category_update.html"
    form_class = LeadCategoryUpdateForm

    def get_queryset(self):
        user = self.request.user

        if user.is_organiser:
            queryset = Lead.objects.filter(organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization)
            """ FILTER FOR THE AGENT THAT'S LOGGED IN """
            queryset = queryset.filter(agent__user=user)

        return queryset

    def get_success_url(self):
        return reverse("leads:lead-detail", kwargs={
            "pk": self.get_object().pk
        })

leads/templates/leads/assign_agent.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
    <div class="max-w-lg mx-auto">
        <div class="border-b border-gray-200">
            <a class="hover:text-blue-500 mt-3" href="{% url 'leads:lead-list' %}">Go back to Leads</a>
        </div>
        <h3>Assign this lead to an Agent</h3>
        <form method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <button class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md text-white" type="submit">
                Submit
            </button>
        </form>
    </div>
{% endblock content %}

leads/templates/leads/category_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">{{ category.name }}</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
        Following lead(s) belong to this category:
      </p>
    </div>
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">
              First Name
            </th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
              Last Name
            </th>
          </tr>
        </thead>
        <tbody>
          {% for lead in category.leads.all %}
              <tr>
                <td class="border-t-2 border-gray-200 px-4 py-3">
                  <a class="hover:text-purple-500" href="{% url 'leads:lead-detail' lead.pk %}">{{ lead.first_name }}</a>
                </td>
                <td class="border-t-2 border-gray-200 px-4 py-3">{{ lead.last_name }}</td>
              </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>

{% endblock content %}

leads/templates/leads/category_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
        These Categories segment the leads
      </p>
    </div>
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Name</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Lead Count</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="px-4 py-3">Unassigned Leads</td>
            <td class="px-4 py-3">{{ unassigned_leads_count }}</td>
          </tr>
          {% for category in categories %}
              <tr>
                <td class="border-t-2 border-gray-200 px-4 py-3">
                  <a class="text-blue-500 hover:text-blue-600" href="{% url 'leads:category-detail' category.pk %}">
                    {{ category.name }}
                  </a>
                </td>
                <td class="border-t-2 border-gray-200 px-4 py-3">{{ category.leads.count }}</td>
              </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>

{% endblock content %}

leads/templates/leads/lead_category_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{ lead.get_full_name }}
        </h1>
        <div class="flex mb-4">
          <a
            href="{% url 'leads:lead-detail' lead.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Overview</a
          >
          <a href="{% url 'leads:lead-category-update' lead.pk %}"
             class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
            Category
          </a>
          <a href="{% url 'leads:lead-update' lead.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
            Update Details
          </a>
        </div>
        <form method="post">
          {% csrf_token %}
          {{ form | crispy }}
          <button class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md text-white" type="submit">
            Submit
          </button>
        </form>
        <a
          href="{% url 'leads:lead-delete' lead.pk %}"
          class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md text-white">
          Delete
        </a>
      </div>
      <img
        alt="ecommerce"
        class="
          lg:w-1/2
          w-full
          lg:h-auto
          h-64
          object-cover object-center
          rounded
        "
        src="https://dummyimage.com/400x400"
      />
    </div>
  </div>
</section>
{% endblock content %}

leads/templates/leads/lead_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
    <div class="max-w-lg mx-auto">
        <div class="border-b border-gray-200">
            <a class="hover:text-blue-500 mt-3" href="{% url 'leads:lead-list' %}">Go back to Leads</a>
        </div>
        <div class="py-5">
            <h2 class="text-2xl">Create a New Lead</h2>
        </div>
        <form method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <button class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md text-white" type="submit">
                Submit
            </button>
        </form>
    </div>
{% endblock content %}

leads/templates/leads/lead_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
    <div class="max-w-lg mx-auto">
        <div class="border-b border-gray-200 py-3">
            <h3 class="text-xl">Are you sure you wanna delete this lead?</h3>
        </div>
        <form method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <button class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md text-white" type="submit">
                Submit
            </button>
        </form>
    </div>
{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends "base.html" %} {% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{ lead.get_full_name }}
        </h1>
        <div class="flex mb-4">
          <a
            href="{% url 'leads:lead-detail' lead.pk %}"
            class="
              flex-grow
              text-indigo-500
              border-b-2 border-indigo-500
              py-2
              text-lg
              px-1
            "
            >Overview</a
          >
          <a href="{% url 'leads:lead-category-update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
            Category
          </a>
          <a
            href="{% url 'leads:lead-update' lead.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
          >
            Update Details
          </a>
        </div>
        <p class="leading-relaxed mb-4">
          Fam locavore kickstarter distillery. Mixtape chillwave tumeric
          sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps
          cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine
          tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.
        </p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Age</span>
          <span class="ml-auto text-gray-900">{{ lead.age }}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Location</span>
          <span class="ml-auto text-gray-900">Palo Alto, CA</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Cell</span>
          <span class="ml-auto text-gray-900">+19083443498</span>
        </div>
        <div class="flex">
          <span class="title-font font-medium text-2xl text-gray-900"
            >$58.00</span
          >
          <button
            class="
              flex
              ml-auto
              text-white
              bg-indigo-500
              border-0
              py-2
              px-6
              focus:outline-none
              hover:bg-indigo-600
              rounded
            "
          >
            Button
          </1button>
          <button
            class="
              rounded-full
              w-10
              h-10
              bg-gray-200
              p-0
              border-0
              inline-flex
              items-center
              justify-center
              text-gray-500
              ml-4
            "
          >
            <svg
              fill="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              class="w-5 h-5"
              viewBox="0 0 24 24"
            >
              <path
                d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"
              ></path>
            </svg>
          </button>
        </div>
      </div>
      <img
        alt="ecommerce"
        class="
          lg:w-1/2
          w-full
          lg:h-auto
          h-64
          object-cover object-center
          rounded
        "
        src="https://dummyimage.com/400x400"
      />
    </div>
  </div>
</section>
{% endblock content %}

leads/templates/leads/lead_list.html
{% extends "base.html" %} {% block content %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
        <div>
            <h1 class="text-4xl text-gray-800">Leads</h1>
            <a class="text-gray hover:text-blue-400" href="{% url 'leads:category-list' %}">View Categories</a>
        </div>
        {% if request.user.is_organiser %}
          <div>
              <a class="text-gray hover:text-blue-400" href="{% url 'leads:lead-create' %}">
                Create a new Lead
              </a>
          </div>
        {% endif %}
    </div>
    <div class="flex flex-wrap -m-4">
      {% for lead in leads %}
        <div class="p-4 lg:w-1/2 md:w-full">
          <div
            class="
              flex
              border-2
              rounded-lg
              border-gray-200 border-opacity-50
              p-8
              sm:flex-row
              flex-col
            "
          >
            <div
              class="
                w-16
                h-16
                sm:mr-8 sm:mb-0
                mb-4
                inline-flex
                items-center
                justify-center
                rounded-full
                bg-indigo-100
                text-indigo-500
                flex-shrink-0
              "
            >
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-8 h-8"
                viewBox="0 0 24 24"
              >
                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
              </svg>
            </div>
            <div class="flex-grow">
              <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                {{ lead.get_full_name }}
              </h2>
              <p class="leading-relaxed text-base">
                Blue bottle crucifix vinyl post-ironic four dollar toast vegan
                taxidermy. Gastropub indxgo juice poutine.
              </p>
              <a
                href="{% url 'leads:lead-detail' lead.pk %}"
                class="mt-3 text-indigo-500 inline-flex items-center"
              >
                View Lead
                <svg
                  fill="none"
                  stroke="currentColor"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  class="w-4 h-4 ml-2"
                  viewBox="0 0 24 24"
                >
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    {% if unassigned_leads.exists %}
      <div class="mt-5 flex flex-wrap -m-4">
        <div class="p-4 w-full">
          <h1 class="text-4xl text-gray-800">Unassigned Leads</h1>
        </div>
        {% for lead in unassigned_leads %}
          <div class="p-4 lg:w-1/2 md:w-full">
            <div
              class="
                flex
                border-2
                rounded-lg
                border-gray-200 border-opacity-50
                p-8
                sm:flex-row
                flex-col
              "
            >
              <div
                class="
                  w-16
                  h-16
                  sm:mr-8 sm:mb-0
                  mb-4
                  inline-flex
                  items-center
                  justify-center
                  rounded-full
                  bg-indigo-100
                  text-indigo-500
                  flex-shrink-0
                "
              >
                <svg
                  fill="none"
                  stroke="currentColor"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  class="w-8 h-8"
                  viewBox="0 0 24 24"
                >
                  <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                </svg>
              </div>
              <div class="flex-grow">
                <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                  {{ lead.get_full_name }}
                </h2>
                <p class="leading-relaxed text-base">
                  Blue bottle crucifix vinyl post-ironic four dollar toast vegan
                  taxidermy. Gastropub indxgo juice poutine.
                </p>
                <a
                  href="{% url 'leads:assign-agent' lead.pk %}"
                  class="mt-3 text-indigo-500 inline-flex items-center"
                >
                  Assign an Agent
                  <svg
                    fill="none"
                    stroke="currentColor"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    class="w-4 h-4 ml-2"
                    viewBox="0 0 24 24"
                  >
                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                  </svg>
                </a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    {% endif %}
  </div>
</section>

{% endblock content %}

leads/templates/leads/lead_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{ lead.get_full_name }}
        </h1>
        <div class="flex mb-4">
          <a
            href="{% url 'leads:lead-detail' lead.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Overview</a
          >
          <a href="{% url 'leads:lead-category-update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
            Category
          </a>
          <a
            href="{% url 'leads:lead-update' lead.pk %}"
            class="
              flex-grow
              text-indigo-500
              border-b-2 border-indigo-500
              py-2
              text-lg
              px-1
            "
          >
            Update Details
          </a>
        </div>
        <form method="post">
          {% csrf_token %}
          {{ form | crispy }}
          <button class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md text-white" type="submit">
            Submit
          </button>
        </form>
        <a
          href="{% url 'leads:lead-delete' lead.pk %}"
          class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md text-white">
          Delete
        </a>
      </div>
      <img
        alt="ecommerce"
        class="
          lg:w-1/2
          w-full
          lg:h-auto
          h-64
          object-cover object-center
          rounded
        "
        src="https://dummyimage.com/400x400"
      />
    </div>
  </div>
</section>
{% endblock content %}