agents/urls.py
from django.urls import path

from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name = "agents"


urlpatterns = [
    path("", AgentListView.as_view(), name="agent-list"),
    path("create/", AgentCreateView.as_view(), name="agent-create"),
    path("<int:pk>/", AgentDetailView.as_view(), name="agent-detail"),
    path("<int:pk>/update/", AgentUpdateView.as_view(), name="agent-update"),
    path("<int:pk>/delete/", AgentDeleteView.as_view(), name="agent-delete"),
]

dj_crm/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from django.contrib import admin
from django.urls import include, path

from leads.views import LandingPageView, SignupView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("reset-password/", PasswordResetView.as_view(), name="reset-password"),
    path("reset-password-done/", PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password-reset-complete/", PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("", LandingPageView.as_view(), name="landing-page"),
    path("leads/", include("leads.urls", namespace="leads")),
    path("agents/", include("agents.urls", namespace="agents")),
]

leads/urls.py
from django.urls import path
from .views import (
    LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView, AssignAgentView,
    CategoryListView, CategoryDetailView, LeadCategoryUpdateView
)


app_name = "leads"


urlpatterns = [
    path("", LeadListView.as_view(), name="lead-list"),
    path("<int:pk>", LeadDetailView.as_view(), name="lead-detail"),
    path("<int:pk>/update/", LeadUpdateView.as_view(), name="lead-update"),
    path("<int:pk>/delete/", LeadDeleteView.as_view(), name="lead-delete"),
    path("<int:pk>/assign-agent/", AssignAgentView.as_view(), name="assign-agent"),
    path("<int:pk>/category/", LeadCategoryUpdateView.as_view(), name="lead-category-update"),
    path("create/", LeadCreateView.as_view(), name="lead-create"),

    path("categories/", CategoryListView.as_view(), name="category-list"),
    path("categories/<int:pk>", CategoryDetailView.as_view(), name="category-detail"),
]

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model


User = get_user_model()


class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name")

agents/views.py
from django.core.mail import send_mail
from django.shortcuts import reverse
from django.views import generic

from leads.models import Agent

from .mixins import OrganiserAndLoginRequiredMixin
from .forms import AgentModelForm


class AgentListView(OrganiserAndLoginRequiredMixin, generic.ListView):
    template_name = "agents/agent_list.html"

    def get_queryset(self):
        organization = self.request.user.userprofile
        """ SHOW ONLY AGENTS WHICH BELONGS TO CURRENT LOGGED IN USER """
        return Agent.objects.filter(organization=organization)


class AgentCreateView(OrganiserAndLoginRequiredMixin, generic.CreateView):
    form_class = AgentModelForm
    template_name = "agents/agent_create.html"

    def get_success_url(self):
        return reverse("agents:agent-list")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organiser = False
        user.save()
        Agent.objects.create(
            user=user,
            organization=self.request.user.userprofile
        )
        send_mail(
            subject="You're invited to be an Agent",
            message="You were added as an Agent by DjCRM. Please login in order to start working.",
            from_email="noreply@djcrm.com",
            recipient_list=[user.email]
        )
        return super(AgentCreateView, self).form_valid(form)


class AgentDetailView(OrganiserAndLoginRequiredMixin, generic.DetailView):
    context_object_name = "agent"
    queryset = Agent.objects.all()
    template_name = "agents/agent_detail.html"


class AgentUpdateView(OrganiserAndLoginRequiredMixin, generic.UpdateView):
    form_class = AgentModelForm
    queryset = Agent.objects.all()
    template_name = "agents/agent_update.html"

    def get_success_url(self):
        return reverse("agents:agent-list")


class AgentDeleteView(OrganiserAndLoginRequiredMixin, generic.DeleteView):
    form_class = AgentModelForm
    queryset = Agent.objects.all()
    template_name = "agents/agent_delete.html"

    def get_success_url(self):
        return reverse("agents:agent-list")

agents/templates/agents/agent_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
    <div class="max-w-lg mx-auto">
        <div class="border-b border-gray-200">
            <a href="{% url 'agents:agent-list' %}">Go back to Agents</a>
        </div>
        <form method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <button class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md text-white" type="submit">
                Submit
            </button>
        </form>
    </div>
{% endblock content %}

agents/templates/agents/agent_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
    <div class="max-w-lg mx-auto">
        <div class="border-b border-gray-200 py-3">
            <h3 class="text-xl">Are you sure you wanna delete this Agent?</h3>
        </div>
        <form method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <button class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md text-white" type="submit">
                Submit
            </button>
        </form>
    </div>
{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends "base.html" %} {% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{ agent.user.username }}
        </h1>
        <div class="flex mb-4">
          <a
            href="{% url 'agents:agent-detail' agent.pk %}"
            class="
              flex-grow
              text-indigo-500
              border-b-2 border-indigo-500
              py-2
              text-lg
              px-1
            "
            >Overview</a
          >
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
            Reviews
          </a>
          <a
            href="{% url 'agents:agent-update' agent.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
          >
            Update Details
          </a>
        </div>
        <p class="leading-relaxed mb-4">
          Fam locavore kickstarter distillery. Mixtape chillwave tumeric
          sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps
          cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine
          tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.
        </p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Age</span>
          <span class="ml-auto text-gray-900">Age</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Location</span>
          <span class="ml-auto text-gray-900">Palo Alto, CA</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Cell</span>
          <span class="ml-auto text-gray-900">+19083443498</span>
        </div>
        <div class="flex">
          <span class="title-font font-medium text-2xl text-gray-900"
            >$58.00</span
          >
          <button
            class="
              flex
              ml-auto
              text-white
              bg-indigo-500
              border-0
              py-2
              px-6
              focus:outline-none
              hover:bg-indigo-600
              rounded
            "
          >
            Button
          </button>
          <button
            class="
              rounded-full
              w-10
              h-10
              bg-gray-200
              p-0
              border-0
              inline-flex
              items-center
              justify-center
              text-gray-500
              ml-4
            "
          >
            <svg
              fill="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              class="w-5 h-5"
              viewBox="0 0 24 24"
            >
              <path
                d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"
              ></path>
            </svg>
          </button>
        </div>
      </div>
      <img
        alt="ecommerce"
        class="
          lg:w-1/2
          w-full
          lg:h-auto
          h-64
          object-cover object-center
          rounded
        "
        src="https://dummyimage.com/400x400"
      />
    </div>
  </div>
</section>
{% endblock content %}

agents/templates/agents/agent_list.html
{% extends "base.html" %} {% block content %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
        <div>
            <h1 class="text-4xl text-gray-800">Agents</h1>
        </div>
        <div>
            <a class="text-gray hover:text-blue-400" href="{% url 'agents:agent-create' %}">Create a new Agent</a>
        </div>
    </div>
    <div class="flex flex-wrap -m-4">
      {% for agent in object_list %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div
          class="
            flex
            border-2
            rounded-lg
            border-gray-200 border-opacity-50
            p-8
            sm:flex-row
            flex-col
          "
        >
          <div
            class="
              w-16
              h-16
              sm:mr-8 sm:mb-0
              mb-4
              inline-flex
              items-center
              justify-center
              rounded-full
              bg-indigo-100
              text-indigo-500
              flex-shrink-0
            "
          >
            <svg
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              class="w-8 h-8"
              viewBox="0 0 24 24"
            >
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
              {{ agent.user.get_full_name }}
            </h2>
            <p class="leading-relaxed text-base">
              Blue bottle crucifix vinyl post-ironic four dollar toast vegan
              taxidermy. Gastropub indxgo juice poutine.
            </p>
            <a
              href="{% url 'agents:agent-detail' agent.pk %}"
              class="mt-3 text-indigo-500 inline-flex items-center"
            >
              View Agent
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-4 h-4 ml-2"
                viewBox="0 0 24 24"
              >
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

{% endblock content %}

agents/templates/agents/agent_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{ agent.user.username }}
        </h1>
        <div class="flex mb-4">
          <a
            href="{% url 'agents:agent-detail' agent.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Overview</a
          >
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
            Reviews
          </a>
          <a
            href="{% url 'agents:agent-update' agent.pk %}"
            class="
              flex-grow
              text-indigo-500
              border-b-2 border-indigo-500
              py-2
              text-lg
              px-1
            "
          >
            Update Details
          </a>
        </div>
        <form method="post">
          {% csrf_token %}
          {{ form | crispy }}
            <button class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md text-white" type="submit">
              Submit
            </button>
        </form>
        <a
          href="{% url 'agents:agent-delete' agent.pk %}"
          class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md text-white">
          Delete
        </a>
      </div>
      <img
        alt="ecommerce"
        class="
          lg:w-1/2
          w-full
          lg:h-auto
          h-64
          object-cover object-center
          rounded
        "
        src="https://dummyimage.com/400x400"
      />
    </div>
  </div>
</section>
{% endblock content %}