agents/urls.py
from django.urls import path

from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name = "agents"


urlpatterns = [
    path("", AgentListView.as_view(), name="agent-list"),
    path("create/", AgentCreateView.as_view(), name="agent-create"),
    path("<int:pk>/", AgentDetailView.as_view(), name="agent-detail"),
    path("<int:pk>/update/", AgentUpdateView.as_view(), name="agent-update"),
    path("<int:pk>/delete/", AgentDeleteView.as_view(), name="agent-delete"),
]

dj_crm/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from django.contrib import admin
from django.urls import include, path

from leads.views import LandingPageView, SignupView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("reset-password/", PasswordResetView.as_view(), name="reset-password"),
    path("reset-password-done/", PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password-reset-complete/", PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("", LandingPageView.as_view(), name="landing-page"),
    path("leads/", include("leads.urls", namespace="leads")),
    path("agents/", include("agents.urls", namespace="agents")),
]

leads/urls.py
from django.urls import path
from .views import (
    LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView, AssignAgentView,
    CategoryListView, CategoryDetailView, LeadCategoryUpdateView
)


app_name = "leads"


urlpatterns = [
    path("", LeadListView.as_view(), name="lead-list"),
    path("<int:pk>", LeadDetailView.as_view(), name="lead-detail"),
    path("<int:pk>/update/", LeadUpdateView.as_view(), name="lead-update"),
    path("<int:pk>/delete/", LeadDeleteView.as_view(), name="lead-delete"),
    path("<int:pk>/assign-agent/", AssignAgentView.as_view(), name="assign-agent"),
    path("<int:pk>/category/", LeadCategoryUpdateView.as_view(), name="lead-category-update"),
    path("create/", LeadCreateView.as_view(), name="lead-create"),

    path("categories/", CategoryListView.as_view(), name="category-list"),
    path("categories/<int:pk>", CategoryDetailView.as_view(), name="category-detail"),
]

templates/base.html
{% load static %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>DJ CRM</title>
    {% comment %} <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet"> {% endcomment %}
    <link href="{% static 'css/tailwind.min.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="max-w-7xl mx-auto">
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock content %}
    </div>
  </body>
</html>

templates/landing.html
{% extends "base.html" %} {% block content %}

<section class="text-gray-600 body-font">
  <div
    class="
      container
      mx-auto
      flex
      px-5
      py-24
      items-center
      justify-center
      flex-col
    "
  >
    <img
      class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded"
      alt="hero"
      src="https://dummyimage.com/720x600"
    />
    <div class="text-center lg:w-2/3 w-full">
      <h1
        class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900"
      >
        CRM built with Django
      </h1>
      <p class="mb-8 leading-relaxed">
        This CRM lets you manage leads efficiently
      </p>
      <div class="flex justify-center">
        <button
          class="
            inline-flex
            text-white
            bg-indigo-500
            border-0
            py-2
            px-6
            focus:outline-none
            hover:bg-indigo-600
            rounded
            text-lg
          "
        >
          Button
        </button>
        <button
          class="
            ml-4
            inline-flex
            text-gray-700
            bg-gray-100
            border-0
            py-2
            px-6
            focus:outline-none
            hover:bg-gray-200
            rounded
            text-lg
          "
        >
          Button
        </button>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/navbar.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">DJ CRM</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      {% if request.user.is_authenticated %}
        <a href="{% url 'leads:lead-list' %}" class="mr-5 hover:text-gray-900 cursor-pointer">Leads</a>
        {% if request.user.is_organiser %}
          <a href="{% url 'agents:agent-list' %}" class="mr-5 hover:text-gray-900 cursor-pointer">Agents</a>
        {% endif %}
      {% endif %}
      {% if not request.user.is_authenticated %}
        <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900 cursor-pointer">Signup</a>
      {% endif %}
    </nav>
    {% if request.user.is_authenticated %}
      Logged in as: {{ request.user.username }}
    <a href="{% url 'logout' %}" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
      Logout
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% else %}
    <a href="{% url 'login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
      Login
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% endif %}
  </div>
</header>